# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Fabric Properties
# check these on https://fabricmc.net/develop
modid=trulyrandom
minecraft_version=24w20a
yarn_mappings=24w20a+build.5
loader_version=0.15.11
# Mod Properties
mod_version=2.0.0
maven_group=com.bawnorton
archives_base_name=trulyrandom
# Dependencies
fabric_version=0.99.0+1.21
sodium_version=mc1.20.6-0.5.8
iris_version=1.7.0+1.20.6
modernfix_version=5.17.3+mc1.20.6
