org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=5
org.gradle.parallel=true
org.gradle.console=rich

mod.group=com.bawnorton
mod.id=trulyrandom
mod.name=TrulyRandom
mod.version=2.9.0
mod.author=Bawnorton
mod.license=MIT
mod.description=Randomise the World

publishing.curseforge=1087424
publishing.modrinth=ZyPspk90